import { Platform } from "./types";

export const TECH_STACK_ICONS: Record<string, string> = {
	TypeScript: '/icons/tech/typescript.svg',
	React: '/icons/tech/react.svg',
	'Next.js': '/icons/tech/nextjs.svg',
	'Tailwind CSS': '/icons/tech/tailwindcss.svg',
	'Google Map': '/icons/tech/googlemap.svg',
	Storybook: '/icons/tech/storybook.svg',
	AWS: '/icons/tech/aws.svg',
	'Github Actions': '/icons/tech/githubactions.svg',
	Docker: '/icons/tech/docker.svg',
	'Faster Image': '/icons/tech/fasterimage.png',
	Jotai: '/icons/tech/jotai.png',
	Jest: '/icons/tech/jest.svg',
	Prisma: '/icons/tech/prisma.svg',
	Postman: '/icons/tech/postman.svg',
	Sentry: '/icons/tech/sentry.svg',
	Jenkins: '/icons/tech/jenkins.svg',
	Zustand: '/icons/tech/zustand.svg',
	Java: '/icons/tech/java.svg',
	Android: '/icons/tech/android.svg',
	Jetpack: '/icons/tech/jetpack.png',
	Mediapipe: '/icons/tech/mediapipe.png',
	SQLite: '/icons/tech/sqlite.svg',
	Material: '/icons/tech/material.svg',
	'Google Cloud Platform': '/icons/tech/gcp.svg',
	JavaScript: '/icons/tech/javascript.svg',
	'React Native': '/icons/tech/reactnative.svg',
	Firebase: '/icons/tech/firebase.svg',
	HTML: '/icons/tech/html.svg',
	CSS: '/icons/tech/css.svg',
	'Node.js': '/icons/tech/nodejs.svg',
	Express: '/icons/tech/express.svg',
	Puppeteer: '/icons/tech/puppeteer.svg',
};

export const PLATFORMS: Platform[] = ['All', 'Web', 'Mobile'];
